# Generated by Django 5.2 on 2025-06-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratocolectivo',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo total del contrato para el período de vigencia especificado.', max_digits=15, null=True, verbose_name='Monto Total del Contrato'),
        ),
        migrations.AlterField(
            model_name='contratoindividual',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo total del contrato para el período de vigencia especificado.', max_digits=15, null=True, verbose_name='Monto Total del Contrato'),
        ),
    ]
