# Generated by Django 5.2 on 2025-06-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoindividual',
            name='tipo_identificacion_contratante',
            field=models.CharField(choices=[('CEDULA', 'Cédula de Identidad'), ('PASAPORTE', 'Pasaporte'), ('RIF', 'Registro de Información Fiscal (RIF)')], help_text='Tipo de documento (Cédula o RIF) de la persona o entidad que paga el contrato.', max_length=20, verbose_name='Tipo de Identificación del Contratante'),
        ),
    ]
