# Generated by Django 5.2.3 on 2025-07-06 01:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usuario',
            name='myapp_usuar_nivel_a_955101_idx',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nivel_acceso',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True, help_text='Controla si el usuario puede iniciar sesión. Desmarcar en lugar de borrar.', verbose_name='Cuenta Activa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Este correo electrónico ya está registrado.'}, help_text='Correo electrónico único, usado para el login.', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('INTERMEDIARIO', 'Intermediario'), ('CLIENTE', 'Cliente'), ('AUDITOR', 'Auditor')], db_index=True, default='CLIENTE', help_text='Clasificación funcional que define los permisos del usuario.', max_length=50, verbose_name='Tipo de Usuario (Rol)'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['tipo_usuario', 'activo'], name='myapp_usuar_tipo_us_b7185e_idx'),
        ),
    ]
