# Generated by Django 5.2.3 on 2025-06-24 20:11

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliadocolectivo',
            name='segundo_apellido',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='afiliadocolectivo',
            name='segundo_nombre',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True, verbose_name='Segundo Nombre'),
        ),
        migrations.AlterField(
            model_name='afiliadoindividual',
            name='segundo_apellido',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='afiliadoindividual',
            name='segundo_nombre',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True, verbose_name='Segundo Nombre'),
        ),
        migrations.AlterField(
            model_name='contratocolectivo',
            name='segundo_apellido',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='contratocolectivo',
            name='segundo_nombre',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True, verbose_name='Segundo Nombre'),
        ),
        migrations.AlterField(
            model_name='contratoindividual',
            name='segundo_apellido',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='contratoindividual',
            name='segundo_nombre',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True, verbose_name='Segundo Nombre'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='segundo_apellido',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='segundo_nombre',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True, verbose_name='Segundo Nombre'),
        ),
        migrations.AlterField(
            model_name='intermediario',
            name='segundo_apellido',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='intermediario',
            name='segundo_nombre',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True, verbose_name='Segundo Nombre'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='segundo_apellido',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='segundo_nombre',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True, verbose_name='Segundo Nombre'),
        ),
        migrations.AlterField(
            model_name='reclamacion',
            name='segundo_apellido',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='reclamacion',
            name='segundo_nombre',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True, verbose_name='Segundo Nombre'),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='segundo_apellido',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='segundo_nombre',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True, verbose_name='Segundo Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='segundo_apellido',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='segundo_nombre',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True, verbose_name='Segundo Nombre'),
        ),
    ]
