# Generated by Django 5.2.3 on 2025-06-26 01:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_afiliadocolectivo_segundo_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Este correo electrónico ya está registrado.'}, help_text='Correo electrónico único.', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo Electrónico'),
        ),
    ]
