# Generated by Django 5.2.3 on 2025-06-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_contratocolectivo_monto_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratocolectivo',
            name='pagos_realizados',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Número de pagos o cuotas abonadas para este contrato hasta la fecha.', verbose_name='Pagos Realizados'),
        ),
        migrations.AlterField(
            model_name='contratoindividual',
            name='pagos_realizados',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Número de pagos o cuotas abonadas para este contrato hasta la fecha.', verbose_name='Pagos Realizados'),
        ),
    ]
