# Generated by Django 5.2.3 on 2025-07-02 01:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Monto base (subtotal) de la factura.', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
